package gui.controller;

import javafx.fxml.FXML;
import domain.OrderController;
import domain.UserController;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ListView;

import javafx.scene.image.ImageView;

import javafx.scene.control.TableView;

import javafx.scene.layout.GridPane;

import javafx.scene.control.Hyperlink;

import javafx.scene.control.TableColumn;

public class SingleOrderOverviewController extends GridPane {
	@FXML
	private GridPane MainPane;
	@FXML
	private TableView TableOrdersView;
	@FXML
	private TableColumn NumberColumnTable;
	@FXML
	private TableColumn DateColumnTable;
	@FXML
	private TableColumn OverviewColumnTable;
	@FXML
	private TableColumn StatusColumnTable;
	@FXML
	private GridPane HeaderPane;
	@FXML
	private ImageView imgDelaware;
	@FXML
	private Hyperlink btnHome;
	@FXML
	private Hyperlink btnNotifications;
	@FXML
	private Hyperlink btnOrders;
	@FXML
	private Label LblUser;
	@FXML
	private TableView OrderDetailsTable;
	@FXML
	private TableColumn IdColumnOrderTable;
	@FXML
	private TableColumn CompanyColumnOrderTable;
	@FXML
	private TableColumn StatusColumnOrderTable;
	@FXML
	private TableColumn PackagingColumnOrderTable;
	@FXML
	private TableColumn TransportServiceColumnOrderTable;
	@FXML
	private TableColumn TrackingColumnOrderTable;
	@FXML
	private TableColumn TotalPriceColumnOrderTable;
	@FXML
	private TableView ProductsTableView;
	@FXML
	private TableColumn ProductColumnTable;
	@FXML
	private TableColumn AmountColumnTable;
	@FXML
	private TableColumn UnitPriceColumnTable;
	@FXML
	private TableColumn TotalPriceColumnTable;
	@FXML
	private ListView CustomerDetailsList;

	private final OrderController oc;
	private UserController uc;

	public SingleOrderOverviewController(OrderController oc, UserController uc) {
		this.oc = oc;
		this.uc = uc;
		
		
	}
	
	// Event Listener on Hyperlink[#btnHome].onAction
	@FXML
	public void showHome(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Hyperlink[#btnNotifications].onAction
	@FXML
	public void showNotifications(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Hyperlink[#btnOrders].onAction
	@FXML
	public void showOrders(ActionEvent event) {
		// TODO Autogenerated
	}
}
