package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.shape.Line;
import javafx.stage.Stage;
import domain.DomainController;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.TableView;
import javafx.scene.Scene;
import javafx.scene.control.Hyperlink;

import javafx.scene.control.TableColumn;

public class OrdersOverviewController extends AnchorPane {
    @FXML
    private AnchorPane MenuPane;
    @FXML
    private Hyperlink btnSupport;
    @FXML
    private Hyperlink btnHome;
    @FXML
    private Hyperlink btnOrders;
    @FXML
    private Hyperlink btnNotifications;
    @FXML
    private AnchorPane HeaderPane;
    @FXML
    private Label LblLogo;
    @FXML
    private Label LblUser;
    @FXML
    private AnchorPane PathPane;
    @FXML
    private Label lblFirstPath;
    @FXML
    private Label LabelNextPage;
    @FXML
    private Label LblSecondPath;
    @FXML
    private Line LineOrderOverview;
    @FXML
    private TableView TableOrdersView;
    @FXML
    private TableColumn NumberColumnTable;
    @FXML
    private TableColumn DateColumnTable;
    @FXML
    private TableColumn CostColumnTable;
    @FXML
    private TableColumn OverviewColumnTable;
    @FXML
    private TableColumn StatusColumnTable;
    @FXML
    private Label lblOrderOverview;

    private DomainController dc;

    public OrdersOverviewController(DomainController dc) {

        this.dc = dc;

        FXMLLoader loader = new FXMLLoader(this.getClass().getResource("/gui/OrdersOverview.fxml"));
        loader.setController(this);
        loader.setRoot(this);

        try {
            loader.load();
        } catch (Exception e) {
            System.out.println(e);
        }


    }

    // Event Listener on Hyperlink[#btnHome].onAction
    @FXML
    public void showHome(ActionEvent event) {
//        if (dc.userIsAdmin(user)) {
            goToAdminScreen();
//        } else {
//            goToWarehousmanScreen();
//        }
    }

    // Event Listener on Hyperlink[#btnOrders].onAction
    @FXML
    public void showOrders(ActionEvent event) {
        // TODO Autogenerated
    }

    // Event Listener on Hyperlink[#btnNotifications].onAction
    @FXML
    public void showNotifications(ActionEvent event) {

    }

    private void goToWarehousmanScreen() {
        WarehousemanOverviewScreenController warehousemanOverviewScreenController = new WarehousemanOverviewScreenController(dc);
        Scene scene = new Scene(warehousemanOverviewScreenController, 600, 600);
        Stage stage = (Stage) this.getScene().getWindow();
        stage.setScene(scene);
        stage.show();

    }

    private void goToAdminScreen() {
        // TODO Auto-generated method stub

    }
}
